version: "3"
services:
  web:
    build: .
    command: gunicorn --bind  core.wsgi:application # Utiliser Gunicorn pour la production
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY='y6n!x54ya621o%b=x^5+gyj2+*s=0iwy(w9c-u2^bsyhghuolg' # Si vous avez besoin d'une clé secrète Django
      - DJANGO_DEBUG=False # Définir sur False en production
